#!/usr/bin/env python3
"""
Comprehensive demonstration of URL pruning debug output.
Shows all the debug statements added to estimate.py
"""
import logging

# Set up detailed logging to see all debug messages
logging.basicConfig(
    level=logging.DEBUG,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)

from bupp.src.estimate.estimate import apply_regex_filters

def demo_pruning():
    """Demonstrate all the pruning debug features."""

    print("=" * 80)
    print("COMPREHENSIVE URL PRUNING DEBUG DEMONSTRATION")
    print("=" * 80)
    print()

    # Scenario 1: Multiple regex patterns
    print("SCENARIO 1: Multiple Regex Patterns")
    print("-" * 80)

    urls_1 = [
        "https://example.com/blog/post-1",
        "https://example.com/blog/post-2",
        "https://example.com/api/v1/users",
        "https://example.com/api/v2/posts",
        "https://example.com/images/logo.png",
        "https://example.com/images/banner.jpg",
        "https://example.com/docs/manual.pdf",
        "https://example.com/about",
        "https://example.com/contact",
    ]

    regexes_1 = [
        r"/api/",                    # Filter API endpoints
        r"\.(png|jpg|jpeg|gif)$",   # Filter images
        r"\.pdf$",                   # Filter PDFs
    ]

    print(f"Input URLs: {len(urls_1)}")
    print(f"Regex Patterns: {regexes_1}")
    print()
    print("Applying filters...")
    print()

    filtered_1, pruned_1 = apply_regex_filters(urls_1, regexes_1)

    print()
    print(f"Results: {len(filtered_1)} kept, {len(pruned_1)} pruned")
    print(f"Kept URLs: {filtered_1}")
    print()

    # Scenario 2: Complex patterns
    print("=" * 80)
    print("SCENARIO 2: Complex Regex Patterns")
    print("-" * 80)

    urls_2 = [
        "https://shop.example.com/products/item-123",
        "https://shop.example.com/products/item-456",
        "https://shop.example.com/cart",
        "https://shop.example.com/checkout",
        "https://blog.example.com/2024/01/post",
        "https://blog.example.com/2024/02/post",
        "https://blog.example.com/archive",
        "https://example.com/home",
    ]

    regexes_2 = [
        r"/products/item-\d+",       # Filter individual product pages
        r"/\d{4}/\d{2}/",           # Filter dated blog posts
    ]

    print(f"Input URLs: {len(urls_2)}")
    print(f"Regex Patterns: {regexes_2}")
    print()
    print("Applying filters...")
    print()

    filtered_2, pruned_2 = apply_regex_filters(urls_2, regexes_2)

    print()
    print(f"Results: {len(filtered_2)} kept, {len(pruned_2)} pruned")
    print(f"Kept URLs: {filtered_2}")
    print()

    # Scenario 3: No matching patterns
    print("=" * 80)
    print("SCENARIO 3: No URLs Match Patterns")
    print("-" * 80)

    urls_3 = [
        "https://example.com/about",
        "https://example.com/contact",
        "https://example.com/services",
    ]

    regexes_3 = [r"/admin/", r"/api/"]

    print(f"Input URLs: {len(urls_3)}")
    print(f"Regex Patterns: {regexes_3}")
    print()
    print("Applying filters...")
    print()

    filtered_3, pruned_3 = apply_regex_filters(urls_3, regexes_3)

    print()
    print(f"Results: {len(filtered_3)} kept, {len(pruned_3)} pruned")
    print()

    # Summary
    print("=" * 80)
    print("SUMMARY")
    print("=" * 80)
    print()
    print("The debug output shows:")
    print("  1. Each individual URL that gets pruned")
    print("  2. The specific regex pattern that matched each URL")
    print("  3. When running the spider:")
    print("     - Active regex patterns being used")
    print("     - All URLs pruned in each batch")
    print("     - New regexes generated by LLM")
    print("     - URLs being removed from the queue")
    print("     - Total collected regexes after each pruning interval")
    print()
    print("To see these messages when running the spider:")
    print("  - Use --log-level DEBUG for detailed per-URL pruning info")
    print("  - Use --log-level INFO for pruning summaries and regex generation")
    print()

if __name__ == "__main__":
    demo_pruning()
